stages:
  - triggers

peerplays-qa-trigger:
  stage: triggers
  trigger:
    include: peerplays-qa-environment/.gitlab-ci.yml
  strategy: depend
  # rules:
  #   - changes:
  #       - peerplays-qa-environment/*

