version: "3"
services:
    ubuntu-for-peerplays:
        build:
            context: ubuntu
            dockerfile: Dockerfile
        image: ubuntu-for-peerplays
        ports:
            - "2000:22"
    peerplays-base:
        build:
            context: peerplays
            dockerfile: Dockerfile
        depends_on:
            - ubuntu-for-peerplays
        image: peerplays-base
