version: "3"
services:
    ubuntu-for-peerplays:
        image: registry.gitlab.com/pbsa/tools-libs/peerplays-utils/ubuntu-for-peerplays
        ports:
            - "2000:22"
    peerplays-base:
        depends_on:
            - ubuntu-for-peerplays
        image: registry.gitlab.com/pbsa/tools-libs/peerplays-utils/peerplays-base
