include:
    - template: Container-Scanning.gitlab-ci.yml

stages:
    - build
    - test

docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:19.03.12-dind
  before_script:
    - docker info
  # Default branch leaves tag empty (= latest tag)
  # All other branches are tagged with the escaped branch name (commit ref slug)
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - docker build -f peerplays-qa-environment/ubuntu/Dockerfile -t "ubuntu-for-peerplays:${tag}" .
    - docker push "ubuntu-for-peerplays:${tag}"
  # Run this job in a branch where a Dockerfile exists
  only:
    - branches