FROM ubuntu:18.04
MAINTAINER PeerPlays Blockchain Standards Association

RUN \
    apt-get update -y && \
      DEBIAN_FRONTEND=noninteractive apt-get install -y \
      autoconf \
      automake \
      bash \
      build-essential \
      ca-certificates \
      cmake \
      dnsutils \
      doxygen \
      expect \
      git \
      graphviz \
      make \
      libbz2-dev \
      libboost-all-dev \
      libncurses5-dev \
      libreadline-dev \
      libsnappy-dev \
      libssl-dev \
      libtool \
      locales \
      mc \
      nano \
      net-tools \
      ntp \
      openssh-server \
      perl \
      pkg-config \
      python3 \
      python3-jinja2 \
      sudo \
      wget \
      zlib1g-dev

ENV HOME /home/peerplays
RUN useradd -rm -d /home/peerplays -s /bin/bash -g root -G sudo -u 1000 peerplays
RUN echo "peerplays  ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/peerplays
RUN chmod 440 /etc/sudoers.d/peerplays

RUN service ssh start
RUN echo 'peerplays:peerplays' | chpasswd

# SSH
EXPOSE 22

WORKDIR /home/peerplays/hive-network

RUN \
    mkdir src

# Clone Hive
ADD hive.diff src
RUN \
    cd src && \
    git clone https://github.com/openhive-network/hive && \
    cd hive && \
    git checkout v1.25.0 && \
    GIT_SSL_NO_VERIFY=true git submodule update --init --recursive

# Configure Hive
RUN \
    cd src/hive && \
    mkdir build && \
    cd build && \
    cmake -DBUILD_HIVE_TESTNET=ON -DSKIP_BY_TX_ID=OFF ..

# Build Hive
RUN \
    cd src/hive/build && \
    make -j$(nproc) cli_wallet hived

# Setup Hive runimage
RUN \
    mv ./src/hive/build/programs/cli_wallet/cli_wallet ./ && \
    mv ./src/hive/build/programs/hived/hived ./ && \
    rm -rf src
ADD config.ini ./hived_data_dir/config.ini
ADD init-network.sh ./init-network.sh

RUN chown peerplays:root -R /home/peerplays/hive-network

# Hive RPC
EXPOSE 28090
# Hive P2P
EXPOSE 28091

# Hive
CMD ["./hived", "-d", "./hived_data_dir"]

